const data=[
    {
        id:1,
        imgUrl:"https://media.istockphoto.com/photos/plate-of-indian-main-course-dal-makhani-and-paneer-butter-masala-picture-id1360457748",
        foodName:"Naan Dal & Shahi Paneer",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:350,
        orignalPrice:450,
    },
    {
        id:2,
        imgUrl:"https://media.istockphoto.com/photos/platter-of-indian-red-kidney-beans-curry-or-rajma-masala-and-rice-picture-id1263719225",
        foodName:"Rajma Chawal",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:280,
        orignalPrice:320,
    },
    {
        id:3,
        imgUrl:"https://media.istockphoto.com/photos/south-indian-dish-idly-or-steamed-cake-served-with-chutney-isolated-picture-id1326414025?s=612x612",
        foodName:"Idli Sambhar",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:200,
        orignalPrice:220,
    },
    {
        id:4,
        imgUrl:"https://media.istockphoto.com/photos/rajasthani-traditional-cuisine-dal-baati-also-know-as-dal-bati-or-picture-id1337466776?s=612x612",
        foodName:"Dal Baati",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:180,
        orignalPrice:200,
    },
    {
        id:5,
        imgUrl:"https://cdn.pixabay.com/photo/2019/04/24/12/11/burger-4152013_960_720.jpg",
        foodName:"Burger",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:35,
        orignalPrice:40,
    },
    {
        id:6,
        imgUrl:"https://cdn.pixabay.com/photo/2016/03/05/21/46/american-1239081_960_720.jpg",
        foodName:"Pizza",
        foodDescription:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde quia repellendus enim reprehenderit veniam. Quasi quisquam perspiciatis saepe alias in",
        currentPrice:350,
        orignalPrice:380,
    },
]
export default data;